<?php

namespace AppBundle\Repository;

/**
 * OptionServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
