<?php

namespace AppBundle\Repository;

/**
 * RdvServOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RdvServOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
