<?php

namespace AppBundle\Repository;

/**
 * RdvServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RdvServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
